server:
  port: 8001


mybatis:
  type-aliases-package: com.ditto.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


spring:
  application:
    name: SPRINGCLOUD-PROVIDER-DEPT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Ditto
    password: 7jh1353148688
    url: jdbc:mysql://localhost:3306/db0?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true

eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
  instance:
    instance-id: SpringCloud-Provider-dept8001
    hostname: localhost
    #默认false隐藏IP
    prefer-ip-address: true

info:
  app:
    name: Ditto-SpringCloud-Provider-8001
  company:
    name: Blog-Ditto

