spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.206.155:3000/Ditto/SpringCloud-Study
          username: jhly0@outlook.com
          password: 7jh1353148688

server:
  port: 6002