server:
  port: 9001

#eureka配置
eureka:
  instance:
    hostname: eureka9001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url: #监控页面配置
      defaultZone: http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
